version: "3.3"

networks:
  default:
    driver: bridge

# TODO: move vars to .env
services:
  pg:
    image: "postgres:12"
    volumes:
      - ./test/dump/kvery_db_template.psql:/docker-entrypoint-initdb.d/kvery_db_template.sql
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=kvery_user
      - POSTGRES_PASSWORD=kvery_pass
      - POSTGRES_DB=kvery_db_template
  mysql:
    image: "mysql:5"
      # volumes:
      #   - mysql-volume:/var/lib/mysql
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kvery_pass
