--
-- PostgreSQL database dump
--

-- Dumped from database version 12.10 (Debian 12.10-1.pgdg110+1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: items; Type: TABLE; Schema: public; Owner: kvery_user
--

CREATE TABLE public.items (
    id integer NOT NULL,
    name text NOT NULL,
    rate integer DEFAULT 0 NOT NULL,
    description text
);


ALTER TABLE public.items OWNER TO kvery_user;

--
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: kvery_user
--

CREATE SEQUENCE public.items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.items_id_seq OWNER TO kvery_user;

--
-- Name: items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: kvery_user
--

ALTER SEQUENCE public.items_id_seq OWNED BY public.items.id;


--
-- Name: items id; Type: DEFAULT; Schema: public; Owner: kvery_user
--

ALTER TABLE ONLY public.items ALTER COLUMN id SET DEFAULT nextval('public.items_id_seq'::regclass);


--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: kvery_user
--

COPY public.items (id, name, rate, description) FROM stdin;
1	Test Item 1	5	Lorem ipsum
2	Test Item 2	0	\N
\.


--
-- Name: items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: kvery_user
--

SELECT pg_catalog.setval('public.items_id_seq', 2, true);


--
-- Name: items items_name_key; Type: CONSTRAINT; Schema: public; Owner: kvery_user
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_name_key UNIQUE (name);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: kvery_user
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

